"""Added columns.

Revision ID: 4569d1e4f590
Revises: fbf9773a43cb
Create Date: 2022-09-06 09:19:33.101815

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '4569d1e4f590'
down_revision = 'fbf9773a43cb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('food_posts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('genre_id', sa.Integer(), nullable=False),
    sa.Column('food_id', sa.Integer(), nullable=False),
    sa.Column('date', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['food_id'], ['foods.id'], ),
    sa.ForeignKeyConstraint(['genre_id'], ['users_genres.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_food_posts_food_id'), 'food_posts', ['food_id'], unique=False)
    op.create_index(op.f('ix_food_posts_genre_id'), 'food_posts', ['genre_id'], unique=False)
    op.create_index(op.f('ix_food_posts_id'), 'food_posts', ['id'], unique=False)
    op.create_index(op.f('ix_food_posts_user_id'), 'food_posts', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_food_posts_user_id'), table_name='food_posts')
    op.drop_index(op.f('ix_food_posts_id'), table_name='food_posts')
    op.drop_index(op.f('ix_food_posts_genre_id'), table_name='food_posts')
    op.drop_index(op.f('ix_food_posts_food_id'), table_name='food_posts')
    op.drop_table('food_posts')
    # ### end Alembic commands ###
