"""Added Users

Revision ID: 54292c2558d0
Revises: 
Create Date: 2022-09-05 12:35:20.535335

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '54292c2558d0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('password_reset_queue',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=64), nullable=False),
    sa.Column('token', sa.String(length=256), nullable=False),
    sa.Column('created_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('expired_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token')
    )
    op.create_index(op.f('ix_password_reset_queue_email'), 'password_reset_queue', ['email'], unique=True)
    op.create_index(op.f('ix_password_reset_queue_id'), 'password_reset_queue', ['id'], unique=False)
    op.create_table('provisional_users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('nickname', sa.String(length=64), nullable=False),
    sa.Column('sex', sa.SmallInteger(), nullable=False),
    sa.Column('birthday', sa.Date(), nullable=False),
    sa.Column('email', sa.String(length=64), nullable=False),
    sa.Column('hashed_password', sa.String(length=128), nullable=False),
    sa.Column('is_teacher', sa.Boolean(), nullable=False),
    sa.Column('token', sa.String(length=256), nullable=False),
    sa.Column('created_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('expired_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token')
    )
    op.create_index(op.f('ix_provisional_users_email'), 'provisional_users', ['email'], unique=True)
    op.create_index(op.f('ix_provisional_users_id'), 'provisional_users', ['id'], unique=False)
    op.create_index(op.f('ix_provisional_users_name'), 'provisional_users', ['name'], unique=False)
    op.create_index(op.f('ix_provisional_users_nickname'), 'provisional_users', ['nickname'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=64), nullable=False),
    sa.Column('hashed_password', sa.String(length=128), nullable=False),
    sa.Column('status', sa.SmallInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_name'), 'users', ['name'], unique=False)
    op.create_index(op.f('ix_users_status'), 'users', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_status'), table_name='users')
    op.drop_index(op.f('ix_users_name'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_provisional_users_nickname'), table_name='provisional_users')
    op.drop_index(op.f('ix_provisional_users_name'), table_name='provisional_users')
    op.drop_index(op.f('ix_provisional_users_id'), table_name='provisional_users')
    op.drop_index(op.f('ix_provisional_users_email'), table_name='provisional_users')
    op.drop_table('provisional_users')
    op.drop_index(op.f('ix_password_reset_queue_id'), table_name='password_reset_queue')
    op.drop_index(op.f('ix_password_reset_queue_email'), table_name='password_reset_queue')
    op.drop_table('password_reset_queue')
    # ### end Alembic commands ###
