"""Added columns.

Revision ID: 6959e40376c9
Revises: 5097683568bc
Create Date: 2022-09-08 09:30:31.840033

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '6959e40376c9'
down_revision = '5097683568bc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_provisional_users_nickname', table_name='provisional_users')
    op.drop_column('provisional_users', 'is_teacher')
    op.drop_column('provisional_users', 'sex')
    op.drop_column('provisional_users', 'birthday')
    op.drop_column('provisional_users', 'nickname')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('provisional_users', sa.Column('nickname', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=64), nullable=False))
    op.add_column('provisional_users', sa.Column('birthday', sa.DATE(), nullable=False))
    op.add_column('provisional_users', sa.Column('sex', mysql.SMALLINT(), autoincrement=False, nullable=False))
    op.add_column('provisional_users', sa.Column('is_teacher', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False))
    op.create_index('ix_provisional_users_nickname', 'provisional_users', ['nickname'], unique=False)
    # ### end Alembic commands ###
