"""Added columns.

Revision ID: c5f2554887ef
Revises: 54292c2558d0
Create Date: 2022-09-06 01:52:20.520326

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c5f2554887ef'
down_revision = '54292c2558d0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users_genres',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_genres_id'), 'users_genres', ['id'], unique=False)
    op.create_index(op.f('ix_users_genres_name'), 'users_genres', ['name'], unique=False)
    op.create_index(op.f('ix_users_genres_user_id'), 'users_genres', ['user_id'], unique=False)
    op.create_table('foods',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('genre_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('img', sa.Text(), nullable=False),
    sa.Column('carbohydrate', sa.Integer(), nullable=False),
    sa.Column('lipid', sa.Integer(), nullable=False),
    sa.Column('protein', sa.Integer(), nullable=False),
    sa.Column('mineral', sa.Integer(), nullable=False),
    sa.Column('vitamin', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['genre_id'], ['users_genres.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_foods_genre_id'), 'foods', ['genre_id'], unique=False)
    op.create_index(op.f('ix_foods_id'), 'foods', ['id'], unique=False)
    op.create_index(op.f('ix_foods_name'), 'foods', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_foods_name'), table_name='foods')
    op.drop_index(op.f('ix_foods_id'), table_name='foods')
    op.drop_index(op.f('ix_foods_genre_id'), table_name='foods')
    op.drop_table('foods')
    op.drop_index(op.f('ix_users_genres_user_id'), table_name='users_genres')
    op.drop_index(op.f('ix_users_genres_name'), table_name='users_genres')
    op.drop_index(op.f('ix_users_genres_id'), table_name='users_genres')
    op.drop_table('users_genres')
    # ### end Alembic commands ###
