"""Added columns.

Revision ID: fbf9773a43cb
Revises: c5f2554887ef
Create Date: 2022-09-06 02:29:09.706841

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fbf9773a43cb'
down_revision = 'c5f2554887ef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('auth', sa.SmallInteger(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'auth')
    # ### end Alembic commands ###
